#version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./laravel:/var/www/html
    ports:
      - "8080:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - mysql
    networks:
      - laravel-net

  # MySQL Database
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: emailenginecore
      MYSQL_ROOT_PASSWORD: "Abcd@1234"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - laravel-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
    networks:
      - laravel-net

networks:
  laravel-net:
